server:
  port: 18000
spring:
  application:
    name: ChineseAddressAnalyzer
  datasource:
    url: jdbc:mysql://47.93.239.109:3306/chineseaddressanlyzer?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    username: xx
    password: sixtoflymysql
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      # 5分钟
      idle-timeout: 300000
