server:
  port: 18000
spring:
  application:
    name: ChineseAddressAnalyzer
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/chineseaddressanlyzer?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      # 5分钟
      idle-timeout: 300000
